# Generated by Django 4.1.7 on 2023-05-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForkAndKnife', '0002_hy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hy',
        ),
    ]
