# Generated by Django 4.1.7 on 2023-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ForkAndKnife", "0012_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(max_length=100),
        ),
    ]
